services:
    # Сервис для OpenSearch
    opensearch:
        image: opensearchproject/opensearch:latest
        container_name: opensearch
        environment:
            - discovery.type=single-node # Однокластеровый узел - один сервер
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m # Ограничение памяти 
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=S!rong_Password100% 
            - plugins.security.disabled=true
            - OPENSEARCH_PLUGINS=k-NN # Поддержка k-NN
            - network.host=0.0.0.0 
        ports:
            - "9200:9200" 
        volumes:
            - opensearch-data:/usr/share/opensearch/data # Место для хранения данных
        restart: always # Перезапускать контейнеры при сбоях

    # Сервис для OpenSearch Dashbords
    dashboards:
        image: opensearchproject/opensearch-dashboards:latest
        container_name: dashboards
        depends_on:
            - opensearch # Dashboards ждет запуска OpenSerach
        environment:
            - OPENSEARCH_HOSTS=["http://opensearch:9200"] 
            - OPENSEARCH_USERNAME=admin
            - OPENSEARCH_PASSWORD=S!rong_Password100%
            - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # Отключение плагина безопасности
        ports:
            - "5601:5601" 
        restart: always

    # Сервис для API на Python
    api:
        build: ./api 
        container_name: api
        environment:
            - OPENSEARCH_URL=http://opensearch:9200 # Путь к OpenSearch для API
            - OPENSEARCH_USER=admin
            - OPENSEARCH_PASSWORD=S!rong_Password100%
            - OLLAMA_HOST=http://host.docker.internal:11434 # Подключаем ollama
        extra_hosts:
              - "host.docker.internal:host-gateway" # для работы ollama 
        ports:
            - "8000:8000" 
        depends_on:
            - opensearch # API ждет запуска OpenSearch
        volumes: 
            - ./api:/app
        restart: always


# Определяем том для данных OpenSearch
volumes:
    opensearch-data:
